version: "3"

services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ~/.ssh/id_rsa:/opt/yijun/.ssh/id_rsa
      - ..:/opt/yijun/code
      - ~/etc/localtime:/opt/yijun/etc/localtime
      - ~/etc/timezone:/opt/yijun/etc/timezone
    command: ["tail -f /dev/null"]
